---
version: 0.2

phases:
  build:
    commands:
      - echo "Login to DockerHub!"
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      # - cd python/codebuild
      # - docker build --tag "techcto/python-codebuild:latest" .
      # - docker push "techcto/python-codebuild:latest"
      # - cd ../duplicity
      # - docker build --tag "techcto/duplicity:latest" .
      # - docker push "techcto/duplicity:latest"
      # - cd ../../mongo
      # - docker build --tag "techcto/mongo:latest" .
      # - docker push "techcto/mongo:latest"
      - chmod 700 build.sh
      - ./build.sh php/alpine/php-fpm-7.2 techcto alpine-php-fpm-7.2
      # - cd ../../aws/php-fpm-7.2
      # - docker build --tag "techcto/aws-php-fpm-7.2:latest" .
      # - docker push "techcto/aws-php-fpm-7.2:latest"
      # - cd ../php-fpm-5.6
      # - docker build --tag "techcto/aws-php-fpm-5.6:latest" .
      # - docker push "techcto/aws-php-fpm-5.6:latest"
  post_build:
    commands:
      - echo "Docker image pushed on `date`"