---
version: 0.2

phases:
  build:
    commands:
      - echo "Login to DockerHub"
      - docker login -u $(DOCKER_HUB_USER) -p $(DOCKER_HUB_PASSWORD)
      - docker build --tag "techcto/docker-php-fpm-7.2:latest"
        --file php/php-fpm-7.2/Dockerfile
      - docker push "techcto/docker-php-fpm-7.2:latest"
  post_build:
    commands:
      - echo "Docker image pushed on `date`"