---
version: 0.2

phases:
  build:
    commands:
      - echo "Login to DockerHub!"
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - chmod 700 build.sh
      # - ./build.sh php/alpine/php-fpm-7.2 techcto alpine-php-fpm-7.2 1.2.2
      # - ./build.sh php/alpine/php-fpm-7.4 techcto alpine-php-fpm-7.4
      # - ./build.sh php/alpine/php-fpm-8.0 techcto alpine-php-fpm-8.0

      # - ./build.sh php/alpine/php-fpm-8.1 techcto alpine-php-fpm-8.1
      
      # - ./build.sh php/alpine/httpd techcto httpd
      # - ./build.sh php/aws/php-fpm-7.2 techcto aws-php-fpm-7.2
      # - ./build.sh php/aws/php-fpm-5.6 techcto aws-php-fpm-5.6
      # - ./build.sh php/aws/php-fpm-7.4 techcto aws-php-fpm-7.4
      - ./build.sh php/aws/php-fpm-8.1 techcto aws-php-fpm-8.1
      # - ./build.sh python/codebuild techcto python-codebuild
      # - ./build.sh packer techcto packer
      # - ./build.sh python/duplicity techcto duplicity
      # - ./build.sh redis techcto redis 6.2
      # - ./build.sh mongo techcto mongo 4

  post_build:
    commands:
      - echo "Docker image pushed on `date`"