version: '2'

volumes:
  client:
  mysql:

networks:
  wordnet:
    driver: bridge

services: 

  ui: 
    build: 
      context: .
      dockerfile: ./Dockerfile.ui
    environment: 
      APP_URL: '${APP_URL}'
      APP_ENV: '${APP_ENV}'
      VIRTUAL_HOST: ${WORDPRESS_WEBSITE_URL}
      VIRTUAL_PORT: ${HTTP_PORT}
    volumes:      
      - client:/var/www/html
    ports:
      - '${HTTP_PORT}:80'
    links:
      - app
    networks:
      wordnet:
        aliases:
          - ${WORDPRESS_WEBSITE_URL}
    restart: always
    tty: true

  app: 
    build:
      context: .
    environment: 
      APP_ENV: '${APP_ENV}'
      APP_DEBUG: '${APP_DEBUG}'
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
      WORDPRESS_ADMIN_USER: '${WORDPRESS_ADMIN_USER}'
      WORDPRESS_ADMIN_PASSWORD: '${WORDPRESS_ADMIN_PASSWORD}'
      WORDPRESS_ADMIN_EMAIL: '${WORDPRESS_ADMIN_EMAIL}'
      WORDPRESS_WEBSITE_URL: '${WORDPRESS_WEBSITE_URL}'
      APP_URL: '${APP_URL}'
    networks:
      - wordnet
    volumes:
      - client:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb:10.3
    command: --sql_mode=""
    environment:
      MYSQL_DATABASE: '${WORDPRESS_DB_NAME}'
      MYSQL_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      MYSQL_USER: '${WORDPRESS_DB_USER}'
    ports: 
      - '${DB_PORT}:3306'
    networks:
      - wordnet
    restart: always
    volumes:
      - mysql:/var/lib/mysql:rw