version: '2'

volumes:
  client:
  mysql:

services: 

  ui: 
    build: 
      context: .
      dockerfile: ./Dockerfile.web
    environment: 
      APP_URL: '${APP_URL}'
      APP_ENV: '${APP_ENV}'
    volumes:      
      - client:/var/www/html
    ports:
      - '${HTTP_PORT}:80'
    links:
      - app
    restart: always
    tty: true

  app: 
    build:
      context: .
    environment: 
      APP_ENV: '${APP_ENV}'
      APP_DEBUG: '${APP_DEBUG}'
      DB_HOST: mysql
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_DATABASE}'
      APP_URL: '${APP_URL}'
    volumes:
      - client:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb:10.3
    command: --sql_mode=""
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USER}'
    ports: 
      - '${DB_PORT}:3306'
    restart: always
    volumes:
      - mysql:/var/lib/mysql:rw